export const cities = [
  "Santiago",
  "Puente Alto",
  "Maipú",
  "La Florida",
  "Las Condes",
  "Antofagasta",
  "Viña del Mar",
  "Valparaíso",
  "Temuco",
  "Concepción",
  "Rancagua",
  "Talca",
  "Arica",
  "Iquique",
  "Puerto Montt",
  "Coquimbo",
  "La Serena",
  "Chillán",
  "Calama",
  "Osorno",
  "Valdivia",
  "Quilpué",
  "Los Ángeles",
  "Copiapó",
  "Curicó",
  "Punta Arenas",
  "San Bernardo",
  "Melipilla",
  "Ovalle",
  "Quillota",
  "Linares",
  "San Antonio",
  "San Felipe",
  "Los Andes",
  "Peñaflor",
  "Machalí",
  "Constitución",
  "Angol",
  "San Fernando",
  "Coronel",
  "Talcahuano",
  "Peñalolén",
  "La Granja",
  "Pudahuel",
  "Estación Central",
  "Recoleta",
  "Providencia",
  "Ñuñoa",
  "Vitacura",
  "Lo Barnechea",
]
